language: node_js
node_js:
  - 10
branches:
  only:
    - master
before_script:
  - yarn global add @angular/cli
  - yarn global add codecov
script:
  - yarn build
  - yarn test-ci
after_success:
  - codecov -t $CODECOV_TOKEN
notifications:
  email:
    on_failure: change
    on_success: change
