language: node_js
node_js:
  - 10
branches:
  only:
    - master
before_script:
  - yarn global add @angular/cli codecov
script:
  - yarn build
  - yarn test-headless
after_success:
  - codecov -f coverage/*.json -t $CODECOV_TOKEN
notifications:
  email:
    on_failure: change
    on_success: change
